version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP порт
      - "15672:15672" # Web-интерфейс RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

  security_monitor:
    build: ./SecurityMonitor
    depends_on:
      - rabbitmq
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 5
          cargo run
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  battery_charge_control_system:
    build: ./BatteryChargeControlSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./BatteryChargeControlSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  central_control_system:
     build: ./CentralControlSystem
     depends_on:
       - security_monitor
     entrypoint:
       - bash
       - -c
       - |
           python3 wait_for_rabbitmq.py rabbitmq user password
           sleep 25
           ./CentralControlSystem
     environment:
       RABBIT_HOST: rabbitmq
       RABBIT_USER: user
       RABBIT_PASS: password
       RABBIT_VHOST: "/"

 
  fire_ignition_system:
    build: ./FireIgnitionSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 2
          ./FireIgnitionSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"
  extinguishing_control_system:
    build: ./ExtinguishingControlSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./ExtinguishingControlSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

 
  situation_control_system:
    build: ./SituationControlSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./SituationControlSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  movement_control_system:
    build: ./MovementControlSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./MovementControlSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  gnss_navigation_system:
    build: ./GNSSNavigationSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./GNSSNavigationSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  ins_navigation_system:
    build: ./INSNavigationSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./INSNavigationSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  complexing_system:
    build: ./ComplexingSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./ComplexingSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  flight_task_authenticator:
    build: ./FlightTaskAuthenticator
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 15
          ./FlightTaskAuthenticator
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  fire_extinguishing_system:
    build: ./FireExtinguishingSystem
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 25
          ./FireExtinguishingSystem
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"
  fps:
    build: ./FPS
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 15
          ./FPS
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"

  connection:
    build: ./Connection
    depends_on:
      - security_monitor
    entrypoint:
      - bash
      - -c
      - |
          python3 wait_for_rabbitmq.py rabbitmq user password
          sleep 5
          ./Connection
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: user
      RABBIT_PASS: password
      RABBIT_VHOST: "/"